### ISSUE TITLE
Deepsleep doesn't work

### ISSUE THREAD

**Issue by assusdan** [XiaomiLandOSS/android_device_xiaomi_land#11]

**Comment by Klozz** [comment]
work fine for me but we can wait for more reviews
![810453db-d2f6-49d6-9338-e932d4804a63](https://user-images.githubusercontent.com/1660388/29344151-981c4e50-81fb-11e7-8160-4072f86ee45c.jpg)

**Comment by Klozz** [comment]
![9e848603-495b-47e8-aa20-8279f2eed306](https://user-images.githubusercontent.com/1660388/29344174-b64ba3b2-81fb-11e7-964f-15da8a3bcedf.jpg)

**Comment by assusdan** [comment]
After reboot deepsleep works for me too.
