### ISSUE TITLE
sensors isn't working for me

### ISSUE THREAD

**Issue by Klozz** [XiaomiLandOSS/android_device_xiaomi_land#12]
![3177614a-daf3-45b8-aa72-7281d38194d8](https://user-images.githubusercontent.com/1660388/29344759-bdb7118c-81ff-11e7-896b-14545fe897e0.jpg)

can any share screenshots about sensors?

**Comment by assusdan** [comment]
Are you testing this on LOS ? 
![screenshot_20170815-124219](https://user-images.githubusercontent.com/7590701/29351792-a7ea099e-827d-11e7-8469-a434dbc079c0.png)
![screenshot_20170815-124258](https://user-images.githubusercontent.com/7590701/29351793-a7f5bb54-827d-11e7-8561-96d24788ff61.png)
![screenshot_20170815-124226](https://user-images.githubusercontent.com/7590701/29351795-a7f79a0a-827d-11e7-9c85-c69f312c55a0.png)
![screenshot_20170815-124248](https://user-images.githubusercontent.com/7590701/29351794-a7f731c8-827d-11e7-9dea-9b347a396571.png)

**Comment by Klozz** [comment]
yes both roms for me have dead sensors :/

**Comment by Klozz** [comment]
fixed xd
